# Generated by Django 5.1.6 on 2025-03-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transaction_description_transaction_fund_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fund_request',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10),
        ),
    ]
