# Generated by Django 5.1.6 on 2025-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_purpose_fundrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
