# Generated by Django 5.1.6 on 2025-03-29 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_fund_amount_alter_fundrequest_amount_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fund_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fundrequest'),
        ),
    ]
