# Generated by Django 5.1.6 on 2025-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_fund_blockchain_id_fundrequest_blockchain_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
