# Generated by Django 5.1.6 on 2025-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_fund_source_alter_fundrequest_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='available_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
