# Generated by Django 5.1.6 on 2025-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_organization_available_funds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='available_funds',
        ),
    ]
